server:
  port: 8080
  error:
    include-stacktrace: never
logging:
  level:
    '[org.hibernate.sql]': debug
    '[org.springframework]': info
    '[org.hibernate]': error
    root: info
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} {%thread} [%-5level] [%c{l}]: %msg%n"
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/prueba_bd?useSSL=false&serverTimezone=America/Bogota
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
ingeneo:
  jwt:
    security:
      enabled: false
    timezone: "America/Bogota"
    issuer: "www.programacionfacil.com"
    token:
      auth:
        path: "/v1.0/oauth/client_credential/accesstoken"
      secret: "suscribete si vez este mensaje"
      expires-in: 3600
    excluded:
      path: "/v1.0/multi,/v1.0/otraexclusion"